In [2]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format
#import matplotlib.pyplot as plt
#%matplotlib inline
import csv

# Hospitals

In [3]:
h = pd.read_csv('Hospital_General_Information.csv', index_col=False)
h.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote,Location
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN,"2505 U S HIGHWAY 431 NORTH\nBOAZ, AL\n"
1,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DE KALB,2568453150,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN,"200 MED CENTER DRIVE\nFORT PAYNE, AL\n"
2,10032,WEDOWEE HOSPITAL,209 NORTH MAIN STREET,WEDOWEE,AL,36278,RANDOLPH,2563572111,Acute Care Hospitals,Government - Hospital District or Authority,...,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"209 NORTH MAIN STREET\nWEDOWEE, AL\n"
3,10095,HALE COUNTY HOSPITAL,508 GREEN STREET,GREENSBORO,AL,36744,HALE,3346243024,Acute Care Hospitals,Government - Local,...,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Below the national average,NaN,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,"508 GREEN STREET\nGREENSBORO, AL\n"
4,10131,CRESTWOOD MEDICAL CENTER,ONE HOSPITAL DR SE,HUNTSVILLE,AL,35801,MADISON,2568823100,Acute Care Hospitals,Proprietary,...,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,"ONE HOSPITAL DR SE\nHUNTSVILLE, AL\n"

# Effective Care

In [4]:
e = pd.read_csv('Timely_and_Effective_Care_-_Hospital.csv', index_col=False)
e.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Condition,Measure ID,Measure Name,Score,Sample,Footnote,Measure Start Date,Measure End Date
0,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Emergency Department,ED_1b,ED1,240,1230,2 - Data submitted were based on a sample of c...,01/01/2016,12/31/2016
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Emergency Department,ED_2b,ED2,72,1130,2 - Data submitted were based on a sample of c...,01/01/2016,12/31/2016
2,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Emergency Department,EDV,Emergency department volume,"Very High (60,000+ patients annually)",NaN,NaN,01/01/2015,12/31/2015
3,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Preventive Care,IMM_2,Immunization for influenza,97,916,2 - Data submitted were based on a sample of c...,10/01/2015,03/31/2016
4,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Preventive Care,IMM_3_OP_27_FAC_ADHPCT,Healthcare workers given influenza vaccination,80,1643,NaN,10/01/2016,03/31/2017

In [5]:
print(e['Score'].describe())
e['Score'].unique()

count            105864
unique              591
top       Not Available
freq              52863
Name: Score, dtype: object

array(['240', '72', 'Very High (60,000+ patients annually)', '97', '80',
       'Not Available', '113', '23', '67', '2', '86', '94', '98', '14',
       '199', '54', 'Medium (20,000 - 39,999 patients annually)', '85',
       '137', '32', '58', '100', '1', '12', '245', '82',
       'Low (0 - 19,999 patients annually)', '95', '118', '25', '13', '44',
       '5', '55', '66', '71', '127', '30', '76', '84', '328', '115',
       'High (40,000 - 59,999 patients annually)', '99', '166', '64', '3',
       '0', '92', '88', '63', '107', '22', '40', '91', '158', '316', '59',
       '60', '83', '46', '324', '254', '110', '10', '262', '105', '19',
       '338', '8', '216', '93', '332', '152', '160', '56', '18', '4',
       '190', '53', '87', '28', '79', '96', '68', '89', '39', '38', '7',
       '6', '238', '47', '174', '90', '11', '416', '197', '78', '150',
       '33', '57', '17', '465', '278', '172', '31', '41', '126', '428',
       '136', '73', '247', '188', '281', '184', '29', '365', '209', '156',
       '424', '203', '213', '42', '390', '120', '50', '35', '374', '200',
       '189', '69', '139', '305', '117', '220', '61', '62', '420', '140',
       '177', '48', '20', '296', '75', '395', '138', '182', '15', '70',
       '266', '45', '187', '128', '234', '132', '336', '124', '142', '279',
       '24', '274', '116', '26', '286', '146', '171', '302', '192', '269',
       '165', '351', '164', '257', '129', '233', '131', '77', '147', '267',
       '81', '36', '301', '149', '282', '108', '16', '221', '122', '300',
       '217', '43', '141', '450', '223', '258', '179', '244', '135', '501',
       '235', '185', '309', '21', '49', '155', '263', '114', '232', '111',
       '9', '207', '204', '289', '237', '112', '191', '34', '415', '51',
       '52', '102', '231', '27', '308', '101', '109', '130', '378', '168',
       '208', '393', '414', '228', '153', '438', '195', '310', '288',
       '194', '65', '401', '394', '162', '285', '104', '320', '181', '119',
       '222', '123', '133', '248', '37', '125', '180', '106', '74', '226',
       '260', '167', '304', '154', '224', '170', '426', '198', '280',
       '121', '261', '134', '148', '178', '341', '173', '103', '411',
       '461', '243', '586', '364', '339', '371', '448', '229', '323',
       '290', '143', '360', '363', '236', '556', '333', '653', '356',
       '349', '159', '387', '484', '329', '218', '314', '206', '389',
       '591', '326', '239', '408', '273', '344', '276', '163', '375',
       '186', '265', '242', '368', '176', '183', '219', '352', '144',
       '214', '520', '322', '359', '350', '205', '679', '358', '635',
       '175', '885', '340', '506', '930', '293', '736', '210', '1098',
       '729', '225', '742', '446', '1239', '392', '822', '1221', '702',
       '927', '720', '255', '662', '657', '712', '292', '409', '1129',
       '749', '841', '319', '894', '250', '169', '419', '161', '212',
       '264', '334', '157', '252', '399', '527', '145', '385', '201',
       '303', '202', '241', '418', '196', '193', '297', '354', '277',
       '317', '253', '215', '230', '406', '517', '437', '283', '330',
       '294', '287', '246', '458', '249', '268', '259', '270', '388',
       '412', '366', '312', '256', '376', '291', '272', '579', '211',
       '306', '367', '227', '284', '456', '347', '345', '346', '396',
       '488', '298', '495', '398', '251', '507', '474', '432', '627',
       '472', '430', '1059', '343', '628', '534', '151', '318', '525',
       '271', '382', '557', '372', '526', '337', '379', '513', '434',
       '417', '845', '462', '895', '447', '425', '584', '542', '580',
       '454', '327', '404', '592', '331', '449', '672', '325', '665',
       '348', '435', '746', '640', '516', '496', '321', '383', '313',
       '562', '498', '436', '490', '355', '573', '934', '468', '618',
       '335', '442', '361', '733', '275', '460', '551', '386', '380',
       '362', '402', '342', '552', '369', '370', '514', '391', '400',
       '381', '494', '357', '641', '445', '703', '469', '531', '529',
       '311', '299', '315', '429', '423', '482', '422', '559', '397',
       '444', '440', '724', '307', '492', '588', '473', '617', '476',
       '502', '295', '544', '477', '405', '642', '587', '493', '384',
       '433', '619', '353', '407', '524', '533', '471', '466', '615',
       '546', '463', '512', '538', '585', '523', '604', '576', '500',
       '515', '673', '528', '593', '571', '548', '654', '377', '734',
       '464', '505', '431', '891', '661', '572', '453', '686', '427',
       '373', '560', '638', '567', '790', '511', '622', '510', '410',
       '598', '459', '561', '483', '497', '644', '632', '441', '535'], dtype=object)

In [6]:
print(e['Measure ID'].describe())
e['Measure ID'].unique()

count                     105864
unique                        22
top       IMM_3_OP_27_FAC_ADHPCT
freq                        4812
Name: Measure ID, dtype: object

array(['ED_1b', 'ED_2b', 'EDV', 'IMM_2', 'IMM_3_OP_27_FAC_ADHPCT', 'OP_1',
       'OP_18b', 'OP_2', 'OP_20', 'OP_21', 'OP_22', 'OP_23', 'OP_29',
       'OP_30', 'OP_31', 'OP_3b', 'OP_4', 'OP_5', 'PC_01', 'STK_4',
       'VTE_5', 'VTE_6'], dtype=object)

## Surveys

In [66]:
s = pd.read_csv('hvbp_hcahps_05_28_2015.csv', index_col=False)
s.head()

,Provider Number,Hospital Name,Address,City,State,ZIP Code,County Name,Communication with Nurses Achievement Points,Communication with Nurses Improvement Points,Communication with Nurses Dimension Score,...,Cleanliness and Quietness of Hospital Environment Improvement Points,Cleanliness and Quietness of Hospital Environment Dimension Score,Discharge Information Achievement Points,Discharge Information Improvement Points,Discharge Information Dimension Score,Overall Rating of Hospital Achievement Points,Overall Rating of Hospital Improvement Points,Overall Rating of Hospital Dimension Score,HCAHPS Base Score,HCAHPS Consistency Score
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,Dothan,AL,36301,HOUSTON,0 out of 10,2 out of 9,2 out of 10,...,2 out of 9,3 out of 10,2 out of 10,3 out of 9,3 out of 10,3 out of 10,2 out of 9,3 out of 10,17,16
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,Boaz,AL,35957,MARSHALL,7 out of 10,3 out of 9,7 out of 10,...,0 out of 9,4 out of 10,6 out of 10,5 out of 9,6 out of 10,5 out of 10,0 out of 9,5 out of 10,51,20
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,Florence,AL,35631,LAUDERDALE,1 out of 10,1 out of 9,1 out of 10,...,0 out of 9,0 out of 10,1 out of 10,5 out of 9,5 out of 10,0 out of 10,0 out of 9,0 out of 10,9,12
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,Opp,AL,36467,COVINGTON,0 out of 10,0 out of 9,0 out of 10,...,5 out of 9,6 out of 10,5 out of 10,8 out of 9,8 out of 10,2 out of 10,4 out of 9,4 out of 10,40,17
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,Luverne,AL,36049,CRENSHAW,0 out of 10,0 out of 9,0 out of 10,...,0 out of 9,1 out of 10,0 out of 10,0 out of 9,0 out of 10,0 out of 10,0 out of 9,0 out of 10,30,15

In [67]:
print(s['Overall Rating of Hospital Achievement Points'].describe())
s['Overall Rating of Hospital Achievement Points'].unique()

count            3074
unique             12
top       0 out of 10
freq             1164
Name: Overall Rating of Hospital Achievement Points, dtype: object

array(['3 out of 10', '5 out of 10', '0 out of 10', '2 out of 10',
       '1 out of 10', '4 out of 10', '9 out of 10', '6 out of 10',
       '10 out of 10', '7 out of 10', 'Not Available', '8 out of 10'], dtype=object)

In [68]:
print(s['Overall Rating of Hospital Improvement Points'].describe())
s['Overall Rating of Hospital Improvement Points'].unique()

count           3074
unique            11
top       0 out of 9
freq            1431
Name: Overall Rating of Hospital Improvement Points, dtype: object

array(['2 out of 9', '0 out of 9', '4 out of 9', '1 out of 9',
       '8 out of 9', '5 out of 9', '7 out of 9', '9 out of 9',
       '3 out of 9', 'Not Available', '6 out of 9'], dtype=object)

In [70]:
print(s['Overall Rating of Hospital Dimension Score'].describe())
s['Overall Rating of Hospital Dimension Score'].unique()

count            3074
unique             12
top       0 out of 10
freq              784
Name: Overall Rating of Hospital Dimension Score, dtype: object

array(['3 out of 10', '5 out of 10', '0 out of 10', '4 out of 10',
       '1 out of 10', '2 out of 10', '9 out of 10', '6 out of 10',
       '10 out of 10', '7 out of 10', 'Not Available', '8 out of 10'], dtype=object)

In [71]:
print(s['HCAHPS Base Score'].describe())
s['HCAHPS Base Score'].unique()

count     3074
unique      82
top          8
freq        86
Name: HCAHPS Base Score, dtype: object

array(['17', '51', '9', '40', '30', '11', '31', '10', '24', '34', '55',
       '16', '45', '33', '47', '59', '38', '8', '27', '72', '80', '3',
       '69', '21', '6', '32', '36', '39', '48', '14', '49', '29', '15',
       '44', '37', '46', '42', 'Not Available', '35', '43', '62', '19',
       '23', '58', '13', '7', '22', '26', '20', '4', '28', '2', '0', '1',
       '25', '65', '67', '57', '5', '71', '12', '61', '18', '50', '56',
       '41', '68', '77', '64', '79', '74', '75', '63', '52', '78', '60',
       '54', '76', '53', '70', '73', '66'], dtype=object)

In [72]:
s['HCAHPS Base Score'].loc[s['HCAHPS Base Score'] == 'Not Available'].count()

32

In [25]:
print(s['HCAHPS Consistency Score'].describe())
s['HCAHPS Consistency Score'].unique()

count     3074
unique      21
top         20
freq       833
Name: HCAHPS Consistency Score, dtype: object

In [13]:
survey['Provider Number'].describe()

count     3,074.00
mean    261,522.02
std     159,765.55
min      10,001.00
25%     110,092.75
50%     260,021.00
75%     390,130.75
max     670,085.00
Name: Provider Number, dtype: float64

## Complications

In [73]:
c = pd.read_csv('Complications_and_Deaths_-_Hospital.csv', index_col=False)
c.head()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Measure Name,Measure ID,Compared to National,Denominator,Score,Lower Estimate,Higher Estimate,Footnote,Measure Start Date,Measure End Date,Location
0,223300,FRANCISCAN CHILDREN'S HOSPITAL & REHAB CENTER,30 WARREN STREET,BRIGHTON,MA,2135,SUFFOLK,6172543800,Deaths among Patients with Serious Treatable C...,PSI_4_SURG_COMP,Not Available,Not Available,Not Available,Not Available,Not Available,19 - Data are shown only for hospitals that pa...,07/01/2014,09/30/2015,"30 WARREN STREET\nBRIGHTON, MA\n(42.349756, -7..."
1,230003,SPECTRUM HEALTH ZEELAND COMMUNITY HOSPITAL,8333 FELCH ST,ZEELAND,MI,49464,OTTAWA,6167724644,Pressure sores,PSI_3_ULCER,No Different than the National Rate,481,0.21,0.00,0.91,NaN,07/01/2014,09/30/2015,"8333 FELCH ST\nZEELAND, MI\n(42.819539, -85.98..."
2,223303,SHRINERS' HOSPITAL FOR CHILDREN (THE),516 CAREW STREET,SPRINGFIELD,MA,1104,HAMPDEN,4137872000,Collapsed lung due to medical treatment,PSI_6_IAT_PTX,Not Available,Not Available,Not Available,Not Available,Not Available,19 - Data are shown only for hospitals that pa...,07/01/2014,09/30/2015,"516 CAREW STREET\nSPRINGFIELD, MA\n(42.120558,..."
3,230003,SPECTRUM HEALTH ZEELAND COMMUNITY HOSPITAL,8333 FELCH ST,ZEELAND,MI,49464,OTTAWA,6167724644,Death rate for stroke patients,MORT_30_STK,Number of Cases Too Small,Not Available,Not Available,Not Available,Not Available,1 - The number of cases/patients is too few to...,07/01/2013,06/30/2016,"8333 FELCH ST\nZEELAND, MI\n(42.819539, -85.98..."
4,230036,MIDMICHIGAN MEDICAL CENTER - ALPENA,1501 W CHISHOLM ST,ALPENA,MI,49707,ALPENA,9893567390,Collapsed lung due to medical treatment,PSI_6_IAT_PTX,No Different than the National Rate,2592,0.41,0.12,0.69,NaN,07/01/2014,09/30/2015,"1501 W CHISHOLM ST\nALPENA, MI\n(45.076857, -8..."

In [83]:
c.describe()

       Provider ID  ZIP Code     Phone Number
count    91,428.00 91,428.00        91,428.00
mean    268,136.62 53,972.20 5,848,062,460.36
std     157,122.36 26,909.11 2,332,079,774.85
min      10,001.00    603.00   936,933,841.00
25%     140,183.50 33,015.25 4,014,532,518.75
50%     260,037.00 55,404.00 6,053,413,350.00
75%     390,220.50 76,028.00 7,877,583,105.00
max     670,120.00 99,929.00 9,898,943,000.00

In [80]:
print(c['Measure ID'].describe())
c['Measure ID'].unique()

count           91428
unique             19
top       PSI_3_ULCER
freq             4812
Name: Measure ID, dtype: object

array(['PSI_4_SURG_COMP', 'PSI_3_ULCER', 'PSI_6_IAT_PTX', 'MORT_30_STK',
       'PSI_10_POST_KIDNEY', 'PSI_9_POST_HEM', 'PSI_15_ACC_LAC',
       'PSI_13_POST_SEPSIS', 'PSI_8_POST_HIP', 'PSI_11_POST_RESP',
       'COMP_HIP_KNEE', 'MORT_30_AMI', 'MORT_30_CABG', 'MORT_30_COPD',
       'MORT_30_HF', 'MORT_30_PN', 'PSI_12_POSTOP_PULMEMB_DVT',
       'PSI_14_POSTOP_DEHIS', 'PSI_90_SAFETY'], dtype=object)

In [75]:
c1 = c.groupby(['Measure Name'])['Measure Name','Denominator','Score','Lower Estimate','Higher Estimate']
c1

# Measures

In [81]:
m = pd.read_csv('Measure_Dates.csv', index_col=False)
m.head()

,Measure Name,Measure ID,Measure Start Quarter,Measure Start Date,Measure End Quarter,Measure End Date
0,ACS Participation data,ACS_REGISTRY,4Q2015,10/01/2015,3Q2016,09/30/2016
1,Fibrinolytic Therapy Received Within 30 Minute...,AMI_7a_HVBP_Baseline,1Q2013,01/01/2013,4Q2013,12/31/2013
2,Fibrinolytic Therapy Received Within 30 Minute...,AMI_7a_HVBP_Performance,1Q2015,01/01/2015,4Q2015,12/31/2015
3,Combined SSI,Combined_SSI_Measure_Score,1Q2013,01/01/2013,4Q2013,12/31/2013
4,Combined SSI,Combined_SSI_Measure_Score_HVBP_Performance,1Q2015,01/01/2015,4Q2015,12/31/2015

In [82]:
m.describe()

,Measure Name,Measure ID,Measure Start Quarter,Measure Start Date,Measure End Quarter,Measure End Date
count,163,163,163,163,163,163
unique,133,161,13,13,10,10
top,Influenza Immunization,Linear Score,1Q2015,01/01/2015,4Q2015,12/31/2015
freq,4,2,43,43,50,50

In [79]:
print(m['Measure ID'].describe())
m['Measure ID'].unique()

count              163
unique             161
top       Linear Score
freq                 2
Name: Measure ID, dtype: object

array(['ACS_REGISTRY', 'AMI_7a_HVBP_Baseline', 'AMI_7a_HVBP_Performance',
       'Combined_SSI_Measure_Score',
       'Combined_SSI_Measure_Score_HVBP_Performance', 'COMP_HIP_KNEE',
       'Composite 1 Q1 to Q3', 'Composite 2 Q5 to Q7',
       'Composite 3 Q4 & Q11', 'Composite 4 Q13 & Q14',
       'Composite 5 Q16 & Q17', 'Composite 6 Q19 & Q20',
       'Composite 7 (Q23 to 25)', 'ED_1b', 'ED_2b', 'EDAC_30_AMI',
       'EDAC_30_HF', 'EDV', 'FUH_30', 'FUH_7', 'HACRP_CAUTI', 'HACRP_CDI',
       'HACRP_CLABSI', 'HACRP_D1', 'HACRP_D2', 'HACRP_MRSA', 'HACRP_PSI90',
       'HACRP_SSI', 'HACRP_Total', 'HAI_1', 'HAI_1_HVBP_Baseline',
       'HAI_1_HVBP_Performance', 'HAI_2', 'HAI_2_HVBP_Baseline',
       'HAI_2_HVBP_Performance', 'HAI_3', 'HAI_3_HVBP_Baseline',
       'HAI_3_HVBP_Performance', 'HAI_4', 'HAI_4_HVBP_Baseline',
       'HAI_4_HVBP_Performance', 'HAI_5', 'HAI_5_HVBP_Baseline',
       'HAI_5_HVBP_Performance', 'HAI_6', 'HAI_6_HVBP_Baseline',
       'HAI_6_HVBP_Performance', 'HBIPS_2', 'HBIPS_3', 'HBIPS_5',
       'HBIPS_6', 'HBIPS_7', 'HCAHPS', 'HCAHPS_HVBP_Baseline',
       'HCAHPS_HVBP_Performance', 'IMM_2', 'IMM_2_HVBP_Baseline',
       'IMM_2_HVBP_Performance', 'IMM_3_OP_27', 'IPFQR_EHR',
       'IPFQR_HCP_FluVac', 'IPFQR_IMM_2', 'IPFQR_PEoC', 'Linear Score',
       'MORT_30_AMI', 'MORT_30_AMI_HVBP_Baseline',
       'MORT_30_AMI_HVBP_Performance', 'MORT_30_CABG', 'MORT_30_COPD',
       'MORT_30_HF', 'MORT_30_HF_HVBP_Baseline',
       'MORT_30_HF_HVBP_Performance', 'MORT_30_PN',
       'MORT_30_PN_HVBP_Baseline', 'MORT_30_PN_HVBP_Performance',
       'MORT_30_STK', 'MSPB_1', 'MSPB_1_HVBP_Baseline',
       'MSPB_1_HVBP_Performance', 'OP_1', 'OP_10', 'OP_11', 'OP_12',
       'OP_13', 'OP_14', 'OP_17', 'OP_18b', 'OP_2', 'OP_20', 'OP_21',
       'OP_22', 'OP_23', 'OP_25', 'OP_26', 'OP_29', 'OP_30', 'OP_31',
       'OP_3b', 'OP_4', 'OP_5', 'OP_8', 'OP_9', 'PAYM_30_AMI',
       'PAYM_30_HF', 'PAYM_30_PN', 'PAYM_90_HIP_KNEE', 'PC_01',
       'PC_01_HVBP_Baseline', 'PC_01_HVBP_Performance', 'PCH_1', 'PCH_14',
       'PCH_15', 'PCH_16', 'PCH_17', 'PCH_18', 'PCH_2', 'PCH_25', 'PCH_3',
       'PSI_10', 'PSI_11', 'PSI_12', 'PSI_13', 'PSI_14', 'PSI_15', 'PSI_3',
       'PSI_4', 'PSI_6', 'PSI_8', 'PSI_9', 'PSI_90',
       'PSI_90_HVBP_Baseline', 'PSI_90_HVBP_Performance', 'Q21', 'Q22',
       'Q8', 'Q9', 'READM_30_AMI', 'READM_30_AMI_HRRP', 'READM_30_CABG',
       'READM_30_CABG_HRRP', 'READM_30_COPD', 'READM_30_COPD_HRRP',
       'READM_30_HF', 'READM_30_HF_HRRP', 'READM_30_HIP_KNEE',
       'READM_30_HIP_KNEE_HRRP', 'READM_30_HOSP_WIDE', 'READM_30_PN',
       'READM_30_PN_HRRP', 'READM_30_STK', 'SM_5', 'SM_PART_GEN_SURG',
       'SM_PART_NURSE', 'Star Rating', 'STK_4', 'SUB_1', 'TOB_1', 'TOB_2',
       'TOB_2a', 'VTE_5', 'VTE_6'], dtype=object)